on: push
name: CI

jobs:
  phpunit:
    strategy:
      matrix:
        php: [7.2, 7.3, 7.4,"8.0", 8.1]
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:${{ matrix.php }}

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install composer dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-scripts
      - name: Run Testsuite
        run: vendor/bin/phpunit tests/

